In [3]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import pandas as pd
from sklearn.model_selection import train_test_split

In [4]:
data = pd.read_csv("merged_df.csv")
data

,Home Team Name,Away Team Name,G_Home,W_Home,L_Home,W-L%_Home,SRS_Home,SOS_Home,W.1_Home,L.1_Home,...,FTA_Away,FT%_Away,ORB_Away,TRB_Away,AST_Away,STL_Away,BLK_Away,TOV_Away,PF_Away,Home Win
0,Davidson,Charleston Southern,32,17,15,0.531,6.45,4.26,8,10,...,643.0,0.666,336.0,1092.0,341.0,176.0,89.0,358.0,620.0,1
1,Dayton,Ball State,32,24,8,0.750,12.98,4.27,15,3,...,696.0,0.718,335.0,1281.0,529.0,203.0,118.0,496.0,658.0,1
2,Fordham,Miami (OH),32,13,19,0.406,-1.97,1.36,7,11,...,689.0,0.691,298.0,1091.0,364.0,238.0,125.0,467.0,642.0,0
3,George Mason,Lafayette,34,20,14,0.588,3.01,1.28,9,9,...,492.0,0.711,205.0,956.0,378.0,148.0,85.0,436.0,514.0,1
4,Virginia Commonwealth,Grambling,35,26,9,0.743,11.57,3.77,14,4,...,747.0,0.663,398.0,1108.0,368.0,292.0,76.0,450.0,658.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5405,Rhode Island,Davidson,35,25,10,0.714,12.88,4.62,13,5,...,587.0,0.753,285.0,1149.0,499.0,163.0,106.0,390.0,583.0,0
5406,Cincinnati,Houston,36,30,6,0.833,18.43,5.49,16,2,...,544.0,0.717,362.0,1138.0,406.0,170.0,113.0,315.0,601.0,1
5407,Harvard,Pennsylvania,28,18,10,0.643,2.30,-2.24,10,4,...,417.0,0.657,267.0,972.0,401.0,181.0,100.0,358.0,501.0,0
5408,Tennessee,Kentucky,32,16,16,0.500,11.28,10.18,8,10,...,980.0,0.704,470.0,1512.0,585.0,229.0,200.0,443.0,716.0,0
5409,Georgia State,UT Arlington,33,20,13,0.606,-0.33,-2.17,12,6,...,749.0,0.681,430.0,1384.0,566.0,266.0,81.0,472.0,691.0,1

In [16]:
X = data.iloc[:,2:64]
y = data.iloc[:,64]

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
model = Sequential([
    Dense(units=64, activation='relu', input_shape=(X_train.shape[1], )),
    Dense(units=32, activation='relu'),
    Dense(units=1, activation='sigmoid')
])

In [19]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [20]:
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/10
136/136 [==============================] - 1s 4ms/step - loss: 36.7702 - accuracy: 0.5823 - val_loss: 9.4736 - val_accuracy: 0.6201
Epoch 2/10
136/136 [==============================] - 0s 4ms/step - loss: 8.5661 - accuracy: 0.5887 - val_loss: 6.4592 - val_accuracy: 0.6451
Epoch 3/10
136/136 [==============================] - 1s 5ms/step - loss: 6.1860 - accuracy: 0.6021 - val_loss: 3.9829 - val_accuracy: 0.6044
Epoch 4/10
136/136 [==============================] - 1s 5ms/step - loss: 6.4725 - accuracy: 0.5957 - val_loss: 7.4615 - val_accuracy: 0.4584
Epoch 5/10
136/136 [==============================] - 1s 5ms/step - loss: 5.4202 - accuracy: 0.5929 - val_loss: 2.6857 - val_accuracy: 0.6109
Epoch 6/10
136/136 [==============================] - 1s 4ms/step - loss: 3.7656 - accuracy: 0.6204 - val_loss: 2.0888 - val_accuracy: 0.6035
Epoch 7/10
136/136 [==============================] - 1s 5ms/step - loss: 3.2604 - accuracy: 0.6088 - val_loss: 2.7673 - val_accuracy: 0.6654
Epoch 8/10
136/136 [==============================] - 0s 2ms/step - loss: 3.9744 - accuracy: 0.5952 - val_loss: 1.6934 - val_accuracy: 0.6423
Epoch 9/10
136/136 [==============================] - 0s 1ms/step - loss: 3.9026 - accuracy: 0.6021 - val_loss: 3.1376 - val_accuracy: 0.5166
Epoch 10/10
136/136 [==============================] - 0s 1ms/step - loss: 3.4346 - accuracy: 0.5922 - val_loss: 1.5246 - val_accuracy: 0.6682

In [22]:
eval_result = model.evaluate(X_test, y_test)

34/34 [==============================] - 0s 3ms/step - loss: 1.5246 - accuracy: 0.6682

In [23]:
eval_result

[1.5246244668960571, 0.668207049369812]